src/mars/dashboard/urls.py
from django.urls import path, include

from . import views
app_name = 'dashboard'
urlpatterns = [
    #URL: .TLD/dashboard/
    path('', views.login_user, name='dashboard'),
    #URL: .TLD/dashboard/user   Requires authentication in session
    path('user/', views.user, name='userpage'),
    #URL: .TLD/dashboard/user/123   Requires authentication for user 123
    path('user/<int:user_id>/', views.user, name='userpage'),
    #URL: .TLD/dashboard/admin      Requires authentication and that user is staff
    path('admin/', views.admin, name='adminpage'),
    
    
    path('create_account', views.create_account, name="create_account"),
    path('edit_account', views.edit_account, name="edit_account"),
    path('toggle_active_account', views.toggle_active_account, name="toggle_active_account"),
    
    path('create_user_key', views.create_user_key, name="create_user_key"),
    path('edit_user_key', views.edit_user_key, name="edit_user_key"),
    path('remove_user_key', views.remove_user_key, name="remove_user_key"),
    
    path('add_new_device', views.add_new_device, name="add_new_device"),
    path('edit_user_device', views.edit_user_device, name="edit_user_device"),
    path('remove_user_device', views.remove_user_device, name="remove_user_device"),



    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),

]

src/mars/mars/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls'), name='dashboard'),
    path('api/v1/activity/', include('activityAPI.urls'), name='api'),
    path('api/v1/data/', include('dataAPI.urls'), name='dataapi'),
    path('', RedirectView.as_view(url='dashboard', permanent=False)),
]

src/mars/dashboard/models.py
from django.conf import settings
from django.db import models


class Api(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    key = models.CharField(max_length=20, blank=False, null=False, unique=True)
    name = models.CharField(max_length=50)
    write_access = models.BooleanField(default=False)
    read_access = models.BooleanField(default=False)
    admin_access = models.BooleanField(default=False)
    time_added = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.name


class Device(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    device_type = models.CharField(max_length=50)
    time_added = models.DateTimeField(auto_now=False, auto_now_add=True)
    def __str__(self):
        return self.name
    

src/mars/dashboard/forms.py
from django import forms

class UserAPICreate(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    write_checkbox = forms.BooleanField(required=False)
    read_checkbox = forms.BooleanField(required=False)
    user_id = forms.IntegerField(required=False)

class CreateAccount(forms.Form):
    password = forms.CharField(max_length=72, required=True)
    username = forms.CharField(max_length=150, required=True)
    fname = forms.CharField(max_length=30, required=False)
    lname = forms.CharField(max_length=150, required=False)
    staff_checkbox = forms.BooleanField(required=False)

class EditAccount(forms.Form):
    password = forms.CharField(max_length=72, required=False)
    username = forms.CharField(max_length=150, required=True)
    fname = forms.CharField(max_length=30, required=False)
    lname = forms.CharField(max_length=150, required=False)
    staff_checkbox = forms.BooleanField(required=False)
    user_id = forms.IntegerField(required=False)

class NewDevice(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    d_type = forms.CharField(max_length=50, required=True)
    user_id = forms.IntegerField(required=False)
    device_id = forms.IntegerField(required=False)

src/mars/dashboard/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotAllowed, HttpResponseRedirect, HttpResponseBadRequest, HttpRequest
from django.core.exceptions import PermissionDenied
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import UserAPICreate, CreateAccount, NewDevice, EditAccount
from .models import Api, Device
from dataAPI.models import Data
from activityAPI.models import Activity
import secrets
import datetime

def index(request):
    return HttpResponse("Hello world, dashboard_index page")

def user(request, user_id = -1):
    #Not an authenticated user
    if not request.user.is_authenticated:
        raise PermissionDenied
    #Use user_id connected to session_id as default,
    #Check if sessioned user is staff and change user to user_id argument
    #else, 403
    user = request.user.id
    if request.user.is_staff:
        if user_id != -1:
            user = user_id
    else:
        if user_id != -1 and user_id != request.user.id:
            raise PermissionDenied

    user_item = User.objects.filter(id=user)[0]
    
    #get api keys from db for selected user
    api_keys_list = Api.objects.filter(user_id=user)
    #get devices from db for selected user
    device_list = Device.objects.filter(user_id=user)
    template = loader.get_template('dashboard/user.html')
    context = {
        'api_keys_list': api_keys_list,
        'user_item': user_item,
        'device_list': device_list,
    }
    return HttpResponse(template.render(context, request))

def time_date_object(time_string):
    time = None
    try:
        #fromisoformat() requires python3.7 or higher. No Z at the end of the string!
        time = datetime.datetime.fromisoformat(time_string)
    except:
        time = None
    return time

def admin(request):
    #Not an authenticated staff user
    if not request.user.is_authenticated or not request.user.is_staff:
        raise PermissionDenied
    users_list = User.objects.all()
    user = request.user.id
    api_keys_list = Api.objects.filter(user_id=user,admin_access=1)
    template = loader.get_template('dashboard/admin.html')
    
    filter_status_text = "All users"
    user_text = None
    user_id = -1
    if request.GET.get("user_filter") is not None:
        try:
            user_id = int(request.GET.get("user_filter"))
            if len(User.objects.filter(id=user_id)) > 0:
                user_text = "User " + User.objects.filter(id=user_id)[0].username
        except:
            user_id = -1
    

    time_start_string = None
    filter_start = None
    if request.GET.get("filter_start") is not None:
        filter_start = time_date_object(request.GET.get("filter_start"))
        if filter_start is not None:
            time_start_string = ": " + filter_start.strftime('%Y-%m-%d')
    time_end_string = None
    filter_end = None
    if request.GET.get("filter_end") is not None:
        filter_end = time_date_object(request.GET.get("filter_end"))
        if filter_end is not None:
            time_end_string = filter_end.strftime('%Y-%m-%d')
    
    if user_text is not None:
        filter_status_text = user_text
    filter_status_text += ": "
    if time_start_string is not None:
        filter_status_text += time_start_string
    filter_status_text += " - "
    if time_end_string is not None:
        filter_status_text += time_end_string


    numbr_of_data_points = Data.objects.filter()
    numbr_of_activities = Activity.objects.filter()
    numbr_of_devices = Device.objects.filter()
    
    if user_id != -1:
        numbr_of_data_points = numbr_of_data_points.filter(user_id=user_id)
        numbr_of_activities = numbr_of_activities.filter(user_id=user_id)
        numbr_of_devices = numbr_of_devices.filter(user_id=user_id)
    
    if filter_end is not None:
        numbr_of_data_points = numbr_of_data_points.filter(time_added__date__lte=filter_end)
        numbr_of_activities = numbr_of_activities.filter(time_started__date__lte=filter_end)

    if filter_start is not None:
        numbr_of_data_points = numbr_of_data_points.filter(time_added__date__gte=filter_start)
        numbr_of_activities = numbr_of_activities.filter(time_started__date__gte=filter_start)
    
    if filter_start is not None and filter_end is not None:
        if filter_start > filter_end:
            numbr_of_data_points = 0
            numbr_of_activities = 0
        else:
            numbr_of_data_points = numbr_of_data_points.count()
            numbr_of_activities = numbr_of_activities.count()
    else:    
        numbr_of_data_points = numbr_of_data_points.count()
        numbr_of_activities = numbr_of_activities.count()
    numbr_of_devices = numbr_of_devices.count()

   # return HttpResponse(numbr_of_data_points)

    context = {
        'users_list': users_list,
        'api_keys_list': api_keys_list,
        'filter_status_text': filter_status_text,
        'numbr_of_data_points': numbr_of_data_points,
        'numbr_of_activities': numbr_of_activities,
        'numbr_of_devices': numbr_of_devices,
    }
    return HttpResponse(template.render(context, request))

def create_account(request):
    if not request.user.is_authenticated and not request.user.is_staff:
        raise PermissionDenied
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])
    else:
        form = CreateAccount(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['fname']
            last_name = form.cleaned_data['lname']
            is_staff = form.cleaned_data['staff_checkbox']

            new_user = User.objects.create(username=username, first_name=first_name, last_name=last_name, is_staff=is_staff)
            new_user.set_password(password)
            new_user.save()
            return HttpResponseRedirect('admin')
        else:
            return HttpResponseBadRequest()

def edit_account(request):
    if not request.user.is_authenticated:
        raise PermissionDenied
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])
    else:
        form = EditAccount(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['fname']
            last_name = form.cleaned_data['lname']
            is_staff = form.cleaned_data['staff_checkbox']
            user_id = form.cleaned_data['user_id']
            if user_id:
                if request.user.id != user_id and not request.user.is_staff:
                    raise PermissionDenied
                user_item = User.objects.filter(id=user_id)[0]
                if password:
                    if len(password) < 8:
                        return HttpResponseBadRequest()
                    user_item.set_password(password)
                user_item.username = username
                user_item.first_name = first_name
                user_item.last_name = last_name
                if request.user.is_staff and is_staff:
                    user_item.is_staff = is_staff
                user_item.save()
                #if password has been set for the current session user
                #return to login page instead of referer since all session for that user is reset, requiring a new login
                if password and user_item.id == request.user.id:
                    return HttpResponseRedirect('login')
                if request.META['HTTP_REFERER']:
                    return HttpResponseRedirect(request.META['HTTP_REFERER'])
                #if unknown where request came from, use .TLD/dashboard
                return HttpResponseRedirect('.')
        return HttpResponseBadRequest()

def toggle_active_account(request):
    if not request.user.is_authenticated and not request.user.is_staff:
        raise PermissionDenied
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])
    else:
        user_id = request.POST['user_id']
        user_item = User.objects.filter(id=user_id)[0]
        if user_item.is_active == 1:
            user_item.is_active = 0
        else:
            user_item.is_active = 1
        user_item.save()
        return HttpResponseRedirect('admin')


def create_user_key(request):
    return_id = request.user.id
    if not request.user.is_authenticated:
        raise PermissionDenied
    if request.method != "POST":
        return HttpResponseNotAllowed(['POST'])
    else:
        form = UserAPICreate(request.POST)
        #validate input
        if form.is_valid():
            name = form.cleaned_data['name']
            write_permission = form.cleaned_data['write_checkbox']
            read_permission = form.cleaned_data['read_checkbox']
            user_id = form.cleaned_data['user_id']
            
            global_api = request.POST.get('global_api')
            admin_access = 0
            if global_api is not None and request.user.is_staff:
                if global_api == "true":
                    #global_api was set to true and user is staff, create Global API key
                    admin_access = 1

            #if user_id wasn't set, set it to return_id
            if not user_id:
                user_id = return_id
            #if user_id and session user aren't the same, check if the session user is staff, if they are, allow changes to other user
            if user_id != request.user.id and request.user.is_staff:
                return_id = user_id    
            new_api_key = secrets.token_hex(10)
            new_api_item = Api(key=new_api_key, name=name, write_access=write_permission, read_access=read_permission, admin_access=admin_access, user_id=return_id)
            new_api_item.save()

src/mars/dashboard/templates/dashboard/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Dashboard</title>
	{% load static %}
	<link rel="stylesheet" href="{% static "dashboard/mini-default.min.css" %}">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Mars">
    <meta name="author" content="Ludwig Johnson">
    <style>
        #user_id{
            text-align: center;
        }
        .responsive-label{
            align-items: center;
        }
        header{
            background-color: #282828 !important;
        }
        header .button{
            background-color: #282828 !important;
            color: #e5e5e5 !important;
        }
        .logo{
            color: #e5e5e5 !important;
        }
        .menu{
            float:middle;
        }
        .tableBtnForm{
            border: none;
            background: transparent;
            margin: 0;
            padding: 0;
        }
        
        
    </style>
</head>
<body>
	<header class="sticky">
		<div class="container">
			<div class="row">
				<div class="col-lg"></div>
				<div class="col-lg-9 col-sm-12 row">
                    <div class="col-lg-11 col-md-10 col-sm-9">
                        <a href="#" class="logo">Mars</a>
                    </div>
                    
                    <div class="col-lg-1 col-md-2 col-sm-3">
                        <a href="{% url 'dashboard:logout' %}" class="button">Logout</a>
                    </div>
				</div>
				<div class="col-lg"></div>
			</div>
		</div>
	  </header>
	<main>
		{% block content %}
        {% endblock %}
	</main>
</body>
</html>

src/mars/dashboard/templates/dashboard/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Dashboard</title>
    {% load static %}
	<link rel="stylesheet" href="{% static "dashboard/mini-default.min.css" %}">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Mars">
    <meta name="author" content="Ludwig Johnson">
    <style>
        body{
            {% load static %}
            background: url({% static "dashboard/bth.png" %}) white;
            background-repeat: no-repeat;
            background-position: right top;
            background-attachment: fixed;
            background-size: 20vh;
        }
        main {
            background: transparent;
            height: 100vh;
            width: 100vw;
            margin: 0 auto;
            padding: 0px;
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: auto;
        }
        @media only screen and (max-width: 1000px) {
            body{
                background-position: center center;
                background-size: 90vw;
                max-height: 100vh;
            }
            main{
                background-color: rgba(255,255,255,0.95)
            }
        }
        @media only screen and (max-width: 550px) {
            .toast{
                width: 75%;
                text-align: center;
            }
        }
        #loginbtn{
            background-color: #448AFF;
            color: #fff;
        }
        #user_id{
            text-align: center;
            left: 30%
        }
        form{
            text-align: center;
            background-color: transparent;
            border: none;
        }
        .toast{
            background-color: #d32f2f;
        }
    </style>
</head>
<body>
	<main>
        <div class="login">
            <form method="post">
                <h1>Login</h1>
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username"><br>
                <input type="password" name="password" placeholder="Password"><br>
                <input type="submit" value="Login" id="loginbtn">
            </form>
        </div>
	</main>
    {% if message %}
        <span class="toast">{{ message }}</span>
    {% endif %}
</body>
</html>